// Generated by https://quicktype.io

export interface BlogsType {
    _id:          string;
    titulo:       string;
    resumen:      string;
    contenido:    string;
    published_at: string;
    createdAt:    string;
    updatedAt:    string;
    __v:          number;
    imagen:       Imagen;
    id:           string;
}

export interface Imagen {
    _id:               string;
    name:              string;
    alternativeText:   string;
    caption:           string;
    hash:              string;
    ext:               EXT;
    mime:              MIME;
    size:              number;
    width:             number;
    height:            number;
    url:               string;
    provider_metadata: ProviderMetadata;
    formats:           Formats;
    provider:          string;
    related:           string[];
    createdAt:         string;
    updatedAt:         string;
    __v:               number;
    id:                string;
}

export enum EXT {
    Jpg = ".jpg",
}

export interface Formats {
    thumbnail?: Medium;
    medium?:    Medium;
    small?:     Medium;
}

export interface Medium {
    name:              string;
    hash:              string;
    ext:               EXT;
    mime:              MIME;
    width:             number;
    height:            number;
    size:              number;
    path:              null;
    url:               string;
    provider_metadata: ProviderMetadata;
}

export enum MIME {
    ImageJPEG = "image/jpeg",
}

export interface ProviderMetadata {
    public_id:     string;
    resource_type: ResourceType;
}

export enum ResourceType {
    Image = "image",
}
