// Generated by https://quicktype.io

export interface CursoTypes {
    _id:          string;
    titulo:       string;
    contenido:    string;
    published_at: string;
    createdAt:    string;
    updatedAt:    string;
    __v:          number;
    imagen:       Imagen;
    id:           string;
}

export interface Imagen {
    _id:               string;
    name:              string;
    alternativeText:   string;
    caption:           string;
    hash:              string;
    ext:               string;
    mime:              string;
    size:              number;
    width:             number;
    height:            number;
    url:               string;
    provider_metadata: ProviderMetadata;
    formats:           Formats;
    provider:          string;
    related:           string[];
    createdAt:         string;
    updatedAt:         string;
    __v:               number;
    id:                string;
}

export interface Formats {
    thumbnail: Large;
    large:     Large;
    medium:    Large;
    small:     Large;
}

export interface Large {
    name:              string;
    hash:              string;
    ext:               string;
    mime:              string;
    width:             number;
    height:            number;
    size:              number;
    path:              null;
    url:               string;
    provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
    public_id:     string;
    resource_type: string;
}
